---

- name: Use kafka_python module to take data and create producer message
  wwt.kafka.kafka_producer:
    host: "{{ messages_kafka_hostname }}"
    port: "{{ messages_kafka_port | default('9092') }}"
    verify_mode: "{{ messages_kafka_verify | default(false) }}"
    topic: "{{ messages_kafka_topic }}"
    data: "{{ messages_kafka_data }}"
