---

- name: Set fact for sw image
  ansible.builtin.set_fact:
    eos_version: "vEOS-Router64-{{ sw_version }}.swi"

- name: Copy sw image
  ansible.builtin.import_tasks: copy_sw_image.yml

- name: Upgrade software image to "{{ sw_version }}"
  ansible.builtin.import_tasks: upgrade_veos.yml


- name: Publish message stating that SW upgrade is done
  ansible.builtin.include_role:
    name: messages_kafka
  vars:
    messages_kafka_data: {
      "sw_version": "{{ sw_version }}",
      "dut": "{{ dut }}",
      "upgrade_status": "post"
    }
