---

- name: Print message complete
  ansible.builtin.debug:
    msg:
      - "veos_sw_upgrade initiated"
      - "{{ dut }}"
      - "{{ sw_version }}"

- name: Publish message stating that SW upgrade is done
  ansible.builtin.include_role:
    name: messages_kafka
  vars:
    messages_kafka_data: {
      "sw_version": "{{ sw_version }}",
      "dut": "{{ dut }}",
      "upgrade_status": "post"
    }
