---

- name: Print message complete
  ansible.builtin.debug:
    msg:
      - "veos_sw_upgrade initiated"
      - "{{ dut }}"
      - "{{ sw_version }}"

- name: Publish message stating that SW upgrade is done
  ansible.builtin.include_role:
    name: messages_kafka
  vars:
    sw_version: "{{ sw_version }}"
    dut: "{{ inventory_hostname }}"
    upgrade_status: "complete"
