---

- name: Netbox Webhook
  hosts: all
  sources:
    - name: netbox webhook
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001

  rules:
    - name: Match EOS SW Version
      condition:
        all:
          - event.payload.data.custom_fields.initiate_upgrade == 'upgrade'
          - event.payload.data.custom_fields.available_sw_version != event.payload.data.custom_fields.current_sw_version

      action:
        run_job_template:
          name: arista_initiate_swim
          organization: Default
          job_args:
            extra_vars:
              dut: "{{ event.payload.data.name }}"
              sw_version: "{{ event.payload.data.custom_fields.available_sw_version }}"

        post_event:
          event:
            upgrade_auth: arista_sw_upgrade_authorized
            dut: "{{ event.payload.data.name }}"
            sw_version: "{{ event.payload.data.custom_fields.available_sw_version  }}"
