---
- name: arista-testing
  hosts: all
  sources:
    - name: kafka event source
      ansible.eda.kafka:
        host: 192.168.2.32
        port: 9092
        topic: ansiblefest2024

  rules:
    - name: Match tests
      condition: event.body.arista_test ==  'arista_test_interfaces'
      action:
        debug:
          msg: "{{ event.body }}"
        run_job_template:
          name: Arista-test-interfaces
          organization: Default
          job_args:
            extra_vars:
              dut: "{{ event.body.device_name }}"
