---
- name: arista-testing
  hosts: all
  sources:
    - name: kafka event source
      ansible.eda.kafka:
        host: fedora01.lab.local
        port: 9092
        verify_mode: false
        topic: ansiblefest2024

  rules:
    - name: Match tests
      condition: event.value == true
      action:
        debug:
          msg: "{{ event.body }}"
        # run_job_template:
        #   name: Arista-test-interfaces
        #   organization: Default
        #   job_args:
        #     extra_vars:
        #       dut: "{{ event.body.value.device_name }}"
