---
- name: Netbox Webhook
  hosts: all
  sources:
    - name: netbox webhook
      ansible.eda.kafka:
        host: fedora01.lab.local
        port: 9092
        verify_mode: false
        topic: ansiblefest2024

  rules:
    - name: Match sw_upgrade
      condition: event.body.value.sw_version == "4.23.4M"

      action:
        run_job_template:
          name: Send message to Kafka
          organization: Default
          job_args:
            extra_vars:
              target_host: "{{ event.payload.data.name }}"
              sw_version: "{{ event.payload.data.custom_fields.available_sw_version }}"
