---

- name: Netbox Webhook test
  hosts: all
  sources:
    - name: netbox webhook
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Match EOS SW Version
      condition: event.payload is defined

      action:
        debug:
          msg: "{{ event.payload.data.custom_fields.available_sw_version }}"
