---

- name: Netbox Webhook test
  hosts: all
  sources:
    - name: netbox webhook
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
        hmac_secret: 'ansiblefest2024'
        hmac_header: 'X-Hook-Signature'
        hmac_format: hex
        hmac_algo: sha512
  rules:
    - name: Match EOS SW Version
      condition: event.payload is defined

      action:
        debug:
          msg: "{{ event.payload }}"
