---

- name: Initiate Arista SWIM process
  gather_facts: false
  hosts: "{{ dut | default('eda-sw100')}}"
  vars_files:
    - "./vars/slack_info.yml"
    - "./vars/kafka_info.yml"
  vars:
    test_name:
      - arista_test_interfaces
        arista_test_routing
        arista_test_http

  tasks:
    - name: Create list of tests to run
      ansible.builtin.include_vars:

    - name: Publish kafka message with test test_results
      bob_private_collection.kafka_python.producer_kafkapy:
        host: "{{ messages_kafka_hostname }}"
        port: "{{ messages_kafka_port }}"
        verify_mode: false
        topic: "{{ messages_kafka_topic }}"
        data: "{{ lookup('ansible.builtin.template', '../templates/arista_test_run.j2') }}"
      loop: "{{ test_name }}"

    # - name: send slack message
