---

- name: Place messages on kafka bus
  hosts: localhost
  gather_facts: false
  vars:
    messages_kafka_hostname: fedora01.lab.local
    # messages_kafka_hostname: 192.168.2.32
    messages_kafka_topic: apache
    messages_kafka_port: 9092
    messages_kafka_data: {
      "test_auth": "message-received"
    }

  tasks:
    - name: Use kafka_python module to take data and create producer message
      kafka_producer:
        host: "{{ messages_kafka_hostname }}"
        port: "{{ messages_kafka_port | default('9092') }}"
        # averify_mode: "{{ messages_kafka_verify | default(false) }}"
        topic: "{{ messages_kafka_topic }}"
        data: "{{ messages_kafka_data }}"
        sasl_mechanism: PLAIN
        sasl_username: admin
        sasl_password: WWTwwt1!
        security_protocol: SASL_PLAINTEXT
