---

- name: Place messages on kafka bus
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Use messages_kafka role to produce messages
      ansible.builtin.include_role:
        name: messages_kafka
