---

- name: Place messages on kafka bus
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Use kafkaprod_module to take data and create producer message
      kafkaprod_module:
        host: fedora01.lab.local
        port: 9092
        verify_mode: false
        topic: ansible-topic
        data: "{'is this my data':'might be'}"
