---

- name: Place messages on kafka bus
  hosts: localhost
  gather_facts: false
  vars:
    current_sw_version: "4.23.4M"
    available_sw_version: "4.22.0F"

  tasks:
    - name: Use messages_kafka role to produce messages
      ansible.builtin.debug:
        msg:
          - "{{ current_sw_version }}"
          - "{{ available_sw_version }}"

    - name: compare
      ansible.builtin.debug:
        msg:
          - "They are not equal"
      when: current_sw_version != available_sw_version
