---

- name: Update Netbox field for current SW version
  hosts: "{{ dut | default('eda-sw100') }}"
  gather_facts: false

  tasks:
    - name: Use roles to update fields and values for current SW Version
      ansible.builtin.include_role:
        name: update_netbox
      vars:
        update_netbox_code_version: 4.22
        dut: eda-sw100
